#!/bin/bash

read -p "Que quiere para comer (Pizza o Hamburguesa)? " resp

if [[ $resp = "pizza" || $resp = "Pizza" ]]; then
	echo "Vamos al dominos"
else
	if [[ $resp = "Hamburguesa" || $resp = "hamburguesa" ]]; then
		echo "Vamos al burguer"
	fi
fi

