#!/bin/bash

while true; do
	echo "1- Nombra fecha actual"
	echo "2- Listar los archivos del directorio actual"
	echo "3- Salir"
	read -p "Elija una de las opciones: " resp
	case $resp in
		1)
			date;;
		2)
			ls -l;;
		3)
			clear
			break;;
		*)
			echo "La opcion no es valida";;
	esac
done
